// *** This code is generated by AI Agent ***

import { test, expect } from '@playwright/test';

test('Google Navigation Test', async ({ page }) => {
  // 1. Navigate to google.com
  console.log('1. Navigating to google.com');
  await page.goto('https://www.google.com');
  console.log('   Navigated to google.com');

  // 2. Click on "I'm Feeling Lucky"
  console.log('2. Clicking on "I\'m Feeling Lucky"');
  await page.getByRole('button', { name: "I'm Feeling Lucky" }).click();
  console.log('   Clicked on "I\'m Feeling Lucky"');

  // 3. Wait for 2 seconds
  console.log('3. Waiting for 2 seconds');
  await page.waitForTimeout(2000);
  console.log('   Waited for 2 seconds');

  // 4. Navigate to thoughtworks.com
  console.log('4. Navigating to thoughtworks.com');
  await page.goto('https://www.thoughtworks.com');
  console.log('   Navigated to thoughtworks.com');

  // 5. Wait for 2 seconds
  console.log('5. Waiting for 2 seconds');
  await page.waitForTimeout(2000);
  console.log('   Waited for 2 seconds');

  // 6. Navigate to google.com again
  console.log('6. Navigating to google.com again');
  await page.goto('https://www.google.com');
  console.log('   Navigated to google.com again');
});
