import { GoogleGenAI } from '@google/genai';
import { mkdirSync, existsSync, writeFileSync } from 'fs';
import path from 'path';
import { exec } from 'child_process';
import util from 'util';
import dotenv from 'dotenv';
dotenv.config();

const execPromise = util.promisify(exec);

const ai = new GoogleGenAI({
  apiKey: "AIzaSyA7D07k9YdO701vF9Cgihd0ZLRCltxqx7o", // ⚠️ Move to .env in production
});

const TESTDIR = '../tests';
const OUTPUT_FILE = 'google1.spec.ts';
const OUTPUT_FILE_PATH = path.join(TESTDIR, OUTPUT_FILE);
const MAX_ATTEMPTS = 3;

if (!existsSync(TESTDIR)) {
  mkdirSync(TESTDIR, { recursive: true });
}

const basePrompt = `Generate an accurate and fully executable Playwright test script in TypeScript. Include meaningful inline comments to explain each step. The output should be code-only, with no explanation or description outside the code block. Also console log each test step. `;

const userPrompt = `Navigate to google.com and click on "I'm Feeling Lucky", wait for 2 seconds,
then navigate to thoughtworks.com and wait for 2 seconds,
then navigate to google.com again`;

async function generateTestScript(errorContext) {
  const promptText = errorContext
    ? `${basePrompt}\n\nThe previous attempt failed with the following error:\n${errorContext}\nPlease correct the code and regenerate.`
    : basePrompt;

  const response = await ai.models.generateContent({
    model: 'gemini-2.0-flash',
    contents: [
      {
        role: 'user',
        parts: [{ text: promptText }],
      },
      {
        role: 'user',
        parts: [{ text: userPrompt }],
      },
    ],
    config: {
      tools: [{ codeExecution: {} }],
    },
  });

  const parts = response?.candidates?.[0]?.content?.parts || [];
  let output = '';

  parts.forEach((part) => {
    if (part.text) {
      const cleaned = part.text.split('\n').filter(line => !line.includes('```')).join('\n');
      output += `${cleaned}\n`;
    } else if (part.executableCode?.code) {
      output += `${part.executableCode.code}\n`;
    }
  });

  return `// *** This code is generated by AI Agent ***\n\n${output}`;
}

async function executeTestScript() {
  try {
    const { stdout, stderr } = await execPromise(`cd ../tests && npx playwright test ${OUTPUT_FILE}`);
    return { success: true, output: stdout };
  } catch (err) {
    return { success: false, output: err.stderr || err.message };
  }
}

async function generateAndDebug() {
  let attempt = 0;
  let success = false;
  let lastError = '';

  while (attempt < MAX_ATTEMPTS && !success) {
    console.log(`🧠 Attempt #${attempt + 1}...`);

    const code = await generateTestScript(lastError);
    writeFileSync(OUTPUT_FILE_PATH, code);

    const result = await executeTestScript();
    success = result.success;
    lastError = result.output;

    if (success) {
      console.log('✅ Test script executed successfully.');
      console.log(result.output);
    } else {
      console.warn(`❌ Script failed on attempt ${attempt + 1}. Error:\n${lastError}`);
    }

    attempt++;
  }

  if (!success) {
    console.error(`💥 All ${MAX_ATTEMPTS} attempts failed. Last error:\n${lastError}`);
  }
}

generateAndDebug();
